apiVersion: v1
kind: Pod
metadata:
  name: pod-0
  labels:
    app: testpod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: testpod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: testpod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: testpod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: testpods-deployment
    labels:
      app: testpods-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: testpod
  template:
    metadata:
      labels:
        app: testpod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testpods-service
  labels:
    app: testpods-service
spec:
  type: ClusterIP
  selector:
    app: testpod
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
